In [ ]:
%load_ext autoreload
%autoreload 2

In [ ]:
import os
import sys
root_path = '../' # This defaults to './', which should be the repository path

sys.path.append(root_path)
from utils import data_handling
from utils import config
import pypsa

In [ ]:
f_names = os.listdir(config.path_to_pypsa_network_sclopf)
f_name_0 = f_names[0] # 0%
f_name_6 = f_names[-1] # 60%

In [ ]:
net6 = pypsa.Network(config.path_to_pypsa_network_sclopf + f_name_6)
net0 = pypsa.Network(config.path_to_pypsa_network_sclopf + f_name_0)

/home/mtitz/.conda/envs/system_split/lib/python3.11/site-packages/pypsa/components.py:323: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attrs.loc[bool_b, "default"] = attrs.loc[bool_b].isin({True, "True"})
/home/mtitz/.conda/envs/system_split/lib/python3.11/site-packages/pypsa/components.py:323: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attrs.loc[bool_b, "default"] = attrs.loc[bool_b].isin({True, "True"})
/home/mtitz/.conda/envs/system_split/lib/python3.11/site-packages/pypsa/components.py:323: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attrs.loc[bool_b, "default"] = attrs.loc[bool_b].isin({True, "True"})
/home/mtitz/.conda/envs/system_split/lib/python3.11/site-packages/pypsa/components.py:323: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attrs.loc[bool_b, "default"] = attrs.loc[bool_b].isin({True, "True"})
INFO:pypsa.io:Imported network sclopf-elec_s_600_ec_lcopt_Co2L0.6.nc has buses, carriers, generators, global_constraints, lines, links, loads, storage_units
/home/mtitz/.conda/envs/system_split/lib/python3.11/site-packages/pypsa/components.py:323: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attrs.loc[bool_b, "default"] = attrs.loc[bool_b].isin({True, "True"})
/home/mtitz/.conda/envs/system_split/lib/python3.11/site-packages/pypsa/components.py:323: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attrs.loc[bool_b, "default"] = attrs.loc[bool_b].isin({True, "True"})
/home/mtitz/.conda/envs/system_split/lib/python3.11/site-packages/pypsa/components.py:323: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attrs.loc[bool_b, "default"] = attrs.loc[bool_b].isin({True, "True"})
/home/mtitz/.conda/envs/system_split/lib/python3.11/site-packages/pypsa/components.py:323: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  attrs.loc[bool_b, "default"] = attrs.loc[bool_b].isin({True, "True"})
INFO:pypsa.io:Imported network sclopf-elec_s_600_ec_lcopt_Co2L0.0.nc has buses, carriers, generators, global_constraints, lines, links, loads, storage_units

In [ ]:
def drop_dummy_lines(net):
    dummy_lines = net.lines[net.lines.s_nom == 0]
    net.mremove("Line", dummy_lines.index)

    return net
net6 = drop_dummy_lines(net6)
net0 = drop_dummy_lines(net0)

In [ ]:
lines6 = net6.lines
lines0 = net0.lines
cols = ["s_nom", "s_nom_opt", "x", "num_parallel", "partition", "orig_partition"]

In [ ]:
set(lines0.columns).difference(set(lines6.columns)), set(lines6.columns).difference(set(lines0.columns))

(set(), {'orig_partition'})

In [ ]:
line_number_groups = lines6.groupby(lines6.index.str.split("_").str[0])

In [ ]:
import numpy as np
sorted_ind = np.argsort(list(lines6.index.str.split("_").str[0]))
lines6 = lines6.iloc[sorted_ind]

In [ ]:
lines6[cols].head()
# line 1 has the same s_nom for both lines.

,s_nom,s_nom_opt,x,num_parallel,partition,orig_partition
Line,,,,,,
0_outagetype2,1698.104541,1698.104541,72.518630,1.000000,"[0, 0, 1]",[0 0 1]
1_outagetype2,2189.659440,2189.659440,45.844545,1.000000,"[0, 0, 1]",[1 0 1]
1_outagetype0,2189.659440,2189.659440,158.372064,0.289474,"[1, 0, 0]",[1 0 1]
10,983.112186,1474.668280,36.913807,0.578947,[2 0 0],[3 0 0]
10_outagetype0,1474.668280,1474.668280,73.827613,0.289474,"[1, 0, 0]",[3 0 0]

In [ ]:
sorted_ind0 = np.argsort(list(lines0.index.str.split("_").str[0]))
lines0 = lines0.iloc[sorted_ind0]
cols = ["s_nom", "s_nom_opt", "x", "num_parallel", "partition"]
lines0[cols].head()
# same thing here. S_nom is the same for all parallel lines.

                     s_nom    s_nom_opt           x  num_parallel  partition
Line
0_outagetype2  1778.741448  1778.741448   72.518630      1.000000  [0, 0, 1]
0              1778.741448  1778.741448   72.518630      1.000000    [0 0 1]
1              3019.532405  3019.532405   35.552912      1.289474    [1 0 1]
1_outagetype0  3019.532405  3019.532405  158.372064      0.289474  [1, 0, 0]
1_outagetype2  3019.532405  3019.532405   45.844545      1.000000  [0, 0, 1]